name: GunSmith
main: com.kraken.gunsmith.GunSmith
version: 1.0.1 (WarZone)
commands: 
     guns:
        description: Controls the GunSmith plugin, and opens a GUI for gun selection.
        usage: /<command> <argument>
     giveGun:
        description: Give GunSmith a gun.
        usage: /<command> <gunName>
     giveAmmo:
        description: Give GunSmith ammunition.
        usage: /<command> <ammoName> 
     giveArmor:
        description: Give GunSmith armor. (Not yet functional)
        usage: /<command> <ammoName> 
     giveGrenade:
        description: Give GunSmith grenades. (Not yet functional)
        usage: /<command> <ammoName>
permissions:
     gunsmith.*:
        description: Permission for all GunSmith commands.
        children:
           gunsmith.guns: true
           gunsmith.shoot: true
     gunsmith.guns:
        description: Permission to use the GunSmith GUI.
     gunsmith.shoot:
        description: Permission to fire GunSmith weapons.