name: GunSmith
main: com.kraken.gunsmith.GunSmith
version: 0.9.2 (beta)
commands: 
     guns:
        description: Controls the GunSmith plugin, and opens a GUI for gun selection..
        usage: /<command> <secondaryCmd>
     giveGun:
        description: Give yourself a gun.
        usage: /<command> <gunName>
     giveAmmo:
        description: Give yourself ammunition.
        usage: /<command> <ammoName>  
     getStat:
        description: Get stats for a particular gun.
        usage: /<command> <gunName> <stat>
     versionGS:
        description: Get the current version of the GunSmith plugin.
        usage: /<command>