name: GunSmith
main: com.kraken.gunsmith.GunSmith
version: 0.8.3 (beta)
commands: 
     guns:
        description: Info for the GunSmith plugin and various gun commands.
        usage: /<command> <secondaryCmd>
     giveGun:
        description: Give yourself a gun.
        usage: /<command> <gunName>
     giveAmmo:
        description: Give yourself ammunition.
        usage: /<command> <ammoName>  
     getStat:
        description: Get stats for a particular gun.
        usage: /<command> <gunName> <stat>
     version:
        description: Get the current version of this plugin.
        usage: /<command>