name: GunSmith
main: com.kraken.gunsmith
version: 1.0 (alpha)
commands: 
     guns:
        description: Info for the GunSmith plugin.
        usage: /<command>
     gun:
        description: Give yourself a gun.
        usage: /<command>