name: GunSmith
main: com.kraken.gunsmith.GunSmith
version: 0.9.3.2 (WarZone)
commands: 
     guns:
        description: Controls the GunSmith plugin, and opens a GUI for gun selection.
        usage: /<command> <secondaryCmd>
     giveGun:
        description: Give GunSmith a gun.
        usage: /<command> <gunName>
     giveAmmo:
        description: Give GunSmith ammunition.
        usage: /<command> <ammoName> 
     giveArmor:
        description: Give GunSmith armor. (Not yet functional)
        usage: /<command> <ammoName> 
     giveGrenade:
        description: Give GunSmith grenades. (Not yet functional)
        usage: /<command> <ammoName>
     versionGS:
        description: Get the current version of the GunSmith plugin.
        usage: /<command>